services:
  service:
    image: copp:service-latest
    container_name: service
    #restart: always
    networks:
      - backend
    depends_on:
      - kafka
      - api_data_base

  api:
    image: copp:api-latest
    container_name: api
    #restart: always
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - kafka
  
  api_data_base:
    image: copp:api-data-base-lasted
    container_name: api-data-base
    #restart: always
    ports:
      - "8001:8001"
    networks:
      - backend

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - backend
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  redis:
    image: 'redis:latest'
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge